spring.application.name=notebookbackend
spring.datasource.url=jdbc:postgresql://postgres:5432/notebookdb
spring.datasource.username=cardo
spring.datasource.password=8xxFS3ApVD9XXnsMocsUxz2rlgTOqFsD4BBxNa1rEJ1yqXiN5a826ho9hHEA8qKK

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

org.gradle.configuration-cache=true